<?php

namespace Database\Seeders;

use App\Models\Activity;
use App\Models\Destination;
use Illuminate\Database\Seeder;

class ActivitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $destinations = Destination::all();
        
        if ($destinations->isEmpty()) {
            $this->command->warn('لا توجد وجهات! يرجى تشغيل DestinationSeeder أولاً.');
            return;
        }

        $activities = [
            // دمشق
            [
                'destination_id' => $destinations->where('name_ar', 'دمشق')->first()->id,
                'name' => 'جولة في البلدة القديمة',
                'type' => 'جولة سياحية',
                'price' => 50.00,
                'rating' => 4.8,
                'location' => 'البلدة القديمة، دمشق',
                'description' => 'جولة شاملة في البلدة القديمة بدمشق، زيارة المسجد الأموي، قصر العظم، والكنائس التاريخية.',
                'is_featured' => true,
                'is_must_visit' => true,
                'is_event' => false,
                'requires_booking' => true,
                'duration_minutes' => 180,
                'duration_label' => '3 ساعات',
                'highlights' => "زيارة المسجد الأموي\nقصر العظم\nالكنائس التاريخية\nالسوق المسقوف",
                'whats_included' => "دليل سياحي محترف\nتذاكر الدخول\nنقل من وإلى الفندق",
                'whats_not_included' => "الوجبات\nالمشروبات\nالنفقات الشخصية",
                'additional_info' => 'يُنصح بارتداء ملابس محتشمة عند زيارة الأماكن الدينية.',
                'payment_policy' => 'الدفع نقداً عند الوصول أو عبر البطاقة.',
                'cancellation_policy' => 'يمكن الإلغاء مجاناً قبل 24 ساعة من موعد الجولة.',
            ],
            [
                'destination_id' => $destinations->where('name_ar', 'دمشق')->first()->id,
                'name' => 'مهرجان دمشق الثقافي',
                'type' => 'مهرجان',
                'price' => 25.00,
                'rating' => 4.5,
                'location' => 'دار الأوبرا، دمشق',
                'description' => 'مهرجان ثقافي سنوي يعرض الفنون والثقافة السورية.',
                'is_featured' => true,
                'is_must_visit' => false,
                'is_event' => true,
                'event_date' => now()->addDays(30)->format('Y-m-d'),
                'requires_booking' => true,
                'duration_minutes' => 240,
                'duration_label' => '4 ساعات',
            ],
            [
                'destination_id' => $destinations->where('name_ar', 'حلب')->first()->id,
                'name' => 'معرض الحرف اليدوية',
                'type' => 'معرض',
                'price' => 15.00,
                'rating' => 4.6,
                'location' => 'قلعة حلب',
                'description' => 'معرض للحرف اليدوية التقليدية السورية في قلعة حلب.',
                'is_featured' => true,
                'is_must_visit' => false,
                'is_event' => true,
                'event_date' => now()->addDays(45)->format('Y-m-d'),
                'requires_booking' => false,
                'duration_minutes' => 180,
                'duration_label' => '3 ساعات',
            ],
            [
                'destination_id' => $destinations->where('name_ar', 'اللاذقية')->first()->id,
                'name' => 'مهرجان الأزهار في اللاذقية',
                'type' => 'مهرجان',
                'price' => 20.00,
                'rating' => 4.7,
                'location' => 'حدائق اللاذقية',
                'description' => 'مهرجان سنوي للأزهار والطبيعة في اللاذقية.',
                'is_featured' => true,
                'is_must_visit' => false,
                'is_event' => true,
                'event_date' => now()->addMonths(2)->format('Y-m-d'),
                'requires_booking' => true,
                'duration_minutes' => 300,
                'duration_label' => '5 ساعات',
            ],
            [
                'destination_id' => $destinations->where('name_ar', 'دمشق')->first()->id,
                'name' => 'مهرجان التراث السوري',
                'type' => 'مهرجان',
                'price' => 30.00,
                'rating' => 4.8,
                'location' => 'المتحف الوطني، دمشق',
                'description' => 'مهرجان يعرض التراث الثقافي السوري الأصيل.',
                'is_featured' => true,
                'is_must_visit' => false,
                'is_event' => true,
                'event_date' => now()->addMonths(3)->format('Y-m-d'),
                'requires_booking' => true,
                'duration_minutes' => 240,
                'duration_label' => '4 ساعات',
            ],
            [
                'destination_id' => $destinations->where('name_ar', 'حلب')->first()->id,
                'name' => 'حفلة موسيقية تراثية',
                'type' => 'حفلة موسيقية',
                'price' => 40.00,
                'rating' => 4.9,
                'location' => 'المسرح البلدي، حلب',
                'description' => 'حفلة موسيقية تراثية تعرض الألحان الشعبية السورية.',
                'is_featured' => true,
                'is_must_visit' => false,
                'is_event' => true,
                'event_date' => now()->addDays(60)->format('Y-m-d'),
                'requires_booking' => true,
                'duration_minutes' => 120,
                'duration_label' => 'ساعتان',
            ],
            [
                'destination_id' => $destinations->where('name_ar', 'دمشق')->first()->id,
                'name' => 'مؤتمر السياحة السورية',
                'type' => 'مؤتمر',
                'price' => 50.00,
                'rating' => 4.5,
                'location' => 'فندق الشام، دمشق',
                'description' => 'مؤتمر سنوي لمناقشة مستقبل السياحة في سوريا.',
                'is_featured' => false,
                'is_must_visit' => false,
                'is_event' => true,
                'event_date' => now()->addMonths(4)->format('Y-m-d'),
                'requires_booking' => true,
                'duration_minutes' => 480,
                'duration_label' => 'يوم كامل',
            ],
            [
                'destination_id' => $destinations->where('name_ar', 'تدمر')->first()->id,
                'name' => 'ورشة عمل التصوير الأثري',
                'type' => 'ورشة عمل',
                'price' => 35.00,
                'rating' => 4.6,
                'location' => 'مدينة تدمر الأثرية',
                'description' => 'ورشة عمل للتصوير الفوتوغرافي في المواقع الأثرية.',
                'is_featured' => false,
                'is_must_visit' => false,
                'is_event' => true,
                'event_date' => now()->addDays(75)->format('Y-m-d'),
                'requires_booking' => true,
                'duration_minutes' => 180,
                'duration_label' => '3 ساعات',
            ],
            // حلب
            [
                'destination_id' => $destinations->where('name_ar', 'حلب')->first()->id,
                'name' => 'زيارة قلعة حلب',
                'type' => 'جولة تاريخية',
                'price' => 40.00,
                'rating' => 4.7,
                'location' => 'قلعة حلب',
                'description' => 'زيارة قلعة حلب التاريخية التي تعود إلى العصور الوسطى.',
                'is_featured' => false,
                'is_must_visit' => true,
                'is_event' => false,
                'requires_booking' => true,
                'duration_minutes' => 120,
                'duration_label' => 'ساعتان',
                'highlights' => "قلعة حلب التاريخية\nالمتحف داخل القلعة\nإطلالة بانورامية على المدينة",
            ],
            [
                'destination_id' => $destinations->where('name_ar', 'حلب')->first()->id,
                'name' => 'جولة في السوق المسقوف',
                'type' => 'جولة تسوق',
                'price' => 30.00,
                'rating' => 4.6,
                'location' => 'السوق المسقوف، حلب',
                'description' => 'جولة في السوق المسقوف الشهير في حلب، أحد أطول الأسواق المسقوفة في العالم.',
                'is_featured' => false,
                'is_must_visit' => false,
                'is_event' => false,
                'requires_booking' => false,
                'duration_minutes' => 150,
                'duration_label' => 'ساعتان ونصف',
            ],
            // تدمر
            [
                'destination_id' => $destinations->where('name_ar', 'تدمر')->first()->id,
                'name' => 'جولة في آثار تدمر',
                'type' => 'جولة أثرية',
                'price' => 60.00,
                'rating' => 4.9,
                'location' => 'مدينة تدمر الأثرية',
                'description' => 'جولة شاملة في مدينة تدمر الأثرية، زيارة المعابد والأعمدة والمسرح الروماني.',
                'is_featured' => true,
                'is_must_visit' => true,
                'is_event' => false,
                'requires_booking' => true,
                'duration_minutes' => 240,
                'duration_label' => '4 ساعات',
                'highlights' => "معبد بعل\nالأعمدة الكولونادية\nالمسرح الروماني\nالمقابر البرجية",
                'whats_included' => "دليل سياحي متخصص\nتذاكر الدخول\nنقل من وإلى الفندق\nوجبة غداء خفيفة",
            ],
            // بصرى
            [
                'destination_id' => $destinations->where('name_ar', 'بصرى')->first()->id,
                'name' => 'زيارة المسرح الروماني في بصرى',
                'type' => 'جولة أثرية',
                'price' => 45.00,
                'rating' => 4.8,
                'location' => 'بصرى الشام',
                'description' => 'زيارة المسرح الروماني في بصرى الذي يعتبر من أجمل المسارح الرومانية في العالم.',
                'is_featured' => true,
                'is_must_visit' => true,
                'is_event' => false,
                'requires_booking' => true,
                'duration_minutes' => 180,
                'duration_label' => '3 ساعات',
            ],
            // اللاذقية
            [
                'destination_id' => $destinations->where('name_ar', 'اللاذقية')->first()->id,
                'name' => 'جولة شاطئية',
                'type' => 'نشاط ترفيهي',
                'price' => 35.00,
                'rating' => 4.4,
                'location' => 'شاطئ اللاذقية',
                'description' => 'استمتع بيوم على شاطئ اللاذقية الجميل.',
                'is_featured' => false,
                'is_must_visit' => false,
                'is_event' => false,
                'requires_booking' => false,
                'duration_minutes' => 480,
                'duration_label' => 'يوم كامل',
            ],
            // معلولا
            [
                'destination_id' => $destinations->where('name_ar', 'معلولا')->first()->id,
                'name' => 'زيارة دير مار تقلا',
                'type' => 'جولة دينية',
                'price' => 35.00,
                'rating' => 4.6,
                'location' => 'معلولا',
                'description' => 'زيارة دير مار تقلا التاريخي في معلولا، القرية التي لا تزال تتحدث الآرامية.',
                'is_featured' => false,
                'is_must_visit' => true,
                'is_event' => false,
                'requires_booking' => true,
                'duration_minutes' => 120,
                'duration_label' => 'ساعتان',
            ],
        ];

        $fieldTranslations = [
            'name' => [
                'جولة في البلدة القديمة' => 'Old City Walking Tour',
                'مهرجان دمشق الثقافي' => 'Damascus Cultural Festival',
                'معرض الحرف اليدوية' => 'Handicrafts Exhibition',
                'مهرجان الأزهار في اللاذقية' => 'Latakia Flower Festival',
                'مهرجان التراث السوري' => 'Syrian Heritage Festival',
                'حفلة موسيقية تراثية' => 'Traditional Music Concert',
                'مؤتمر السياحة السورية' => 'Syrian Tourism Conference',
                'ورشة عمل التصوير الأثري' => 'Archaeological Photography Workshop',
                'زيارة قلعة حلب' => 'Aleppo Citadel Visit',
                'جولة في السوق المسقوف' => 'Covered Souq Tour',
                'جولة في آثار تدمر' => 'Palmyra Ruins Tour',
                'زيارة المسرح الروماني في بصرى' => 'Bosra Roman Theater Visit',
                'جولة شاطئية' => 'Beach Day Tour',
                'زيارة دير مار تقلا' => 'Saint Thecla Monastery Visit',
            ],
            'type' => [
                'جولة سياحية' => 'Sightseeing Tour',
                'مهرجان' => 'Festival',
                'معرض' => 'Exhibition',
                'حفلة موسيقية' => 'Music Concert',
                'مؤتمر' => 'Conference',
                'ورشة عمل' => 'Workshop',
                'جولة تاريخية' => 'Historical Tour',
                'جولة تسوق' => 'Shopping Tour',
                'جولة أثرية' => 'Archaeological Tour',
                'نشاط ترفيهي' => 'Leisure Activity',
                'جولة دينية' => 'Religious Tour',
            ],
            'location' => [
                'البلدة القديمة، دمشق' => 'Old City, Damascus',
                'دار الأوبرا، دمشق' => 'Opera House, Damascus',
                'قلعة حلب' => 'Aleppo Citadel',
                'حدائق اللاذقية' => 'Latakia Gardens',
                'المتحف الوطني، دمشق' => 'National Museum, Damascus',
                'المسرح البلدي، حلب' => 'Municipal Theater, Aleppo',
                'فندق الشام، دمشق' => 'Al Sham Hotel, Damascus',
                'مدينة تدمر الأثرية' => 'Ancient City of Palmyra',
                'السوق المسقوف، حلب' => 'Covered Souq, Aleppo',
                'بصرى الشام' => 'Bosra al-Sham',
                'شاطئ اللاذقية' => 'Latakia Beach',
                'معلولا' => 'Maaloula',
            ],
            'description' => [
                'جولة شاملة في البلدة القديمة بدمشق، زيارة المسجد الأموي، قصر العظم، والكنائس التاريخية.' => 'Comprehensive tour of Damascus Old City including the Umayyad Mosque, Azm Palace, and historic churches.',
                'مهرجان ثقافي سنوي يعرض الفنون والثقافة السورية.' => 'Annual cultural festival showcasing Syrian arts and heritage.',
                'معرض للحرف اليدوية التقليدية السورية في قلعة حلب.' => 'Exhibition of traditional Syrian handicrafts at Aleppo Citadel.',
                'مهرجان سنوي للأزهار والطبيعة في اللاذقية.' => 'Annual flower and nature festival in Latakia.',
                'مهرجان يعرض التراث الثقافي السوري الأصيل.' => 'Festival celebrating authentic Syrian cultural heritage.',
                'حفلة موسيقية تراثية تعرض الألحان الشعبية السورية.' => 'Traditional concert featuring Syrian folk melodies.',
                'مؤتمر سنوي لمناقشة مستقبل السياحة في سوريا.' => 'Annual conference discussing the future of tourism in Syria.',
                'ورشة عمل للتصوير الفوتوغرافي في المواقع الأثرية.' => 'Photography workshop focused on archaeological sites.',
                'زيارة قلعة حلب التاريخية التي تعود إلى العصور الوسطى.' => 'Visit to the historic Aleppo Citadel dating back to the Middle Ages.',
                'جولة في السوق المسقوف الشهير في حلب، أحد أطول الأسواق المسقوفة في العالم.' => 'Guided tour in Aleppo famous covered souq, one of the longest covered markets in the world.',
                'جولة شاملة في مدينة تدمر الأثرية، زيارة المعابد والأعمدة والمسرح الروماني.' => 'Comprehensive tour of ancient Palmyra including temples, colonnades, and the Roman theater.',
                'زيارة المسرح الروماني في بصرى الذي يعتبر من أجمل المسارح الرومانية في العالم.' => 'Visit Bosra Roman theater, considered one of the best-preserved Roman theaters worldwide.',
                'استمتع بيوم على شاطئ اللاذقية الجميل.' => 'Enjoy a relaxing day on the beautiful Latakia beach.',
                'زيارة دير مار تقلا التاريخي في معلولا، القرية التي لا تزال تتحدث الآرامية.' => 'Visit the historic Saint Thecla Monastery in Maaloula, the village where Aramaic is still spoken.',
            ],
            'duration_label' => [
                '3 ساعات' => '3 hours',
                '4 ساعات' => '4 hours',
                '5 ساعات' => '5 hours',
                'ساعتان' => '2 hours',
                'يوم كامل' => 'Full day',
                'ساعتان ونصف' => '2.5 hours',
            ],
            'highlights' => [
                "زيارة المسجد الأموي\nقصر العظم\nالكنائس التاريخية\nالسوق المسقوف" => "Visit Umayyad Mosque\nAzm Palace\nHistoric Churches\nCovered Souq",
                "قلعة حلب التاريخية\nالمتحف داخل القلعة\nإطلالة بانورامية على المدينة" => "Historic Aleppo Citadel\nMuseum inside the citadel\nPanoramic city view",
                "معبد بعل\nالأعمدة الكولونادية\nالمسرح الروماني\nالمقابر البرجية" => "Temple of Bel\nColonnaded Street\nRoman Theater\nTower Tombs",
            ],
            'whats_included' => [
                "دليل سياحي محترف\nتذاكر الدخول\nنقل من وإلى الفندق" => "Professional tour guide\nEntry tickets\nHotel pickup and drop-off",
                "دليل سياحي متخصص\nتذاكر الدخول\nنقل من وإلى الفندق\nوجبة غداء خفيفة" => "Specialized tour guide\nEntry tickets\nHotel pickup and drop-off\nLight lunch",
            ],
            'whats_not_included' => [
                "الوجبات\nالمشروبات\nالنفقات الشخصية" => "Meals\nDrinks\nPersonal expenses",
            ],
            'additional_info' => [
                'يُنصح بارتداء ملابس محتشمة عند زيارة الأماكن الدينية.' => 'Modest clothing is recommended when visiting religious sites.',
            ],
            'payment_policy' => [
                'الدفع نقداً عند الوصول أو عبر البطاقة.' => 'Payment is accepted in cash on arrival or by card.',
            ],
            'cancellation_policy' => [
                'يمكن الإلغاء مجاناً قبل 24 ساعة من موعد الجولة.' => 'Free cancellation is available up to 24 hours before the tour.',
            ],
        ];

        foreach ($activities as $activity) {
            Activity::updateOrCreate(
                [
                    'destination_id' => $activity['destination_id'],
                    'name_ar' => $activity['name'],
                ],
                [
                'destination_id' => $activity['destination_id'],
                'name_ar' => $activity['name'],
                'name_en' => $fieldTranslations['name'][$activity['name']] ?? $activity['name'],
                'type_ar' => $activity['type'],
                'type_en' => $fieldTranslations['type'][$activity['type']] ?? $activity['type'],
                'price' => $activity['price'] ?? null,
                'rating' => $activity['rating'] ?? 0,
                'location_ar' => $activity['location'] ?? null,
                'location_en' => isset($activity['location']) ? ($fieldTranslations['location'][$activity['location']] ?? $activity['location']) : null,
                'description_ar' => $activity['description'] ?? null,
                'description_en' => isset($activity['description']) ? ($fieldTranslations['description'][$activity['description']] ?? $activity['description']) : null,
                'is_featured' => $activity['is_featured'] ?? false,
                'is_must_visit' => $activity['is_must_visit'] ?? false,
                'is_event' => $activity['is_event'] ?? false,
                'event_date' => $activity['event_date'] ?? null,
                'requires_booking' => $activity['requires_booking'] ?? false,
                'duration_minutes' => $activity['duration_minutes'] ?? null,
                'duration_label' => isset($activity['duration_label']) ? ($fieldTranslations['duration_label'][$activity['duration_label']] ?? $activity['duration_label']) : null,
                'highlights_ar' => $activity['highlights'] ?? null,
                'highlights_en' => isset($activity['highlights']) ? ($fieldTranslations['highlights'][$activity['highlights']] ?? $activity['highlights']) : null,
                'whats_included_ar' => $activity['whats_included'] ?? null,
                'whats_included_en' => isset($activity['whats_included']) ? ($fieldTranslations['whats_included'][$activity['whats_included']] ?? $activity['whats_included']) : null,
                'whats_not_included_ar' => $activity['whats_not_included'] ?? null,
                'whats_not_included_en' => isset($activity['whats_not_included']) ? ($fieldTranslations['whats_not_included'][$activity['whats_not_included']] ?? $activity['whats_not_included']) : null,
                'additional_info_ar' => $activity['additional_info'] ?? null,
                'additional_info_en' => isset($activity['additional_info']) ? ($fieldTranslations['additional_info'][$activity['additional_info']] ?? $activity['additional_info']) : null,
                'payment_policy_ar' => $activity['payment_policy'] ?? null,
                'payment_policy_en' => isset($activity['payment_policy']) ? ($fieldTranslations['payment_policy'][$activity['payment_policy']] ?? $activity['payment_policy']) : null,
                'cancellation_policy_ar' => $activity['cancellation_policy'] ?? null,
                'cancellation_policy_en' => isset($activity['cancellation_policy']) ? ($fieldTranslations['cancellation_policy'][$activity['cancellation_policy']] ?? $activity['cancellation_policy']) : null,
                'custom_sections_ar' => null,
                'custom_sections_en' => null,
                ]
            );
        }
    }
}
